import { defineStrings } from '@/lib/i18n';

export const PREMIUM_S = defineStrings({
  he: {
    close: 'סגירה',
    title: 'בלי פרסומות. עם כל הארכיון.',
    subtitle: 'המנוי מממן את המערכת ומשאיר את החדשות נקיות, בשבילכם ובשביל כולם.',
    premiumName: 'פרימיום',
    premiumPrice: '[מחיר] ₪ לחודש',
    premiumFeatures: ['בלי פרסומות בכלל', 'כל הארכיון, עם חיפוש', 'תג תומך/ת בפרופיל'],
    familyName: 'משפחתי',
    familyPrice: '[מחיר] ₪ לחודש · עד 5 בני משפחה',
    familyFeatures: ['כל מה שבפרימיום, לכל אחד', 'עד 5 בני משפחה', 'לכל אחד ההגדרות והשפה שלו'],
    ribbon: 'מומלץ',
    join: 'להצטרפות',
    current: 'המסלול הנוכחי',
    joinPremium: 'להצטרפות לפרימיום',
    renew: 'חידוש אוטומטי. ביטול בכל עת בהגדרות החנות.',
    supporter: 'תומך/ת',
    thanks: 'אתם תומכים. תודה.',
    activePremium: 'המנוי שלכם פעיל: בלי פרסומות, כל הארכיון והחיפוש.',
    activeFamilyOwner: 'המנוי המשפחתי שלכם פעיל. אפשר להזמין עד 4 בני משפחה.',
    activeFamilyMember: 'אתם חלק ממנוי משפחתי: בלי פרסומות, כל הארכיון והחיפוש.',
    manageFamily: 'ניהול בני המשפחה',
    donateLead: 'רוצים לתמוך גם בלי מנוי?',
    donate: 'לתרומה לעמותה',
    soonTitle: 'המנויים ייפתחו בקרוב',
    soonText: 'בקרוב אפשר יהיה להצטרף לפרימיום ולמנוי המשפחתי ישירות מהאפליקציה, דרך Google Play.',
    soonWhatsapp: 'כבר מנויי פרימיום בוואטסאפ? אתם מזוהים אוטומטית לפי מספר הטלפון: נכנסים לאפליקציה עם אותו מספר, והמנוי פעיל.',
    soonDonate: 'רוצים לתמוך כבר עכשיו? אפשר לתרום לעמותה.',
    ok: 'הבנתי',
  },
  en: {
    close: 'Close',
    title: 'No ads. The whole archive.',
    subtitle: 'Your subscription funds the service and keeps the news clean, for you and for everyone.',
    premiumName: 'Premium',
    premiumPrice: '[price] ₪ a month',
    premiumFeatures: ['No ads at all', 'The whole archive, with search', 'Supporter badge on your profile'],
    familyName: 'Family',
    familyPrice: '[price] ₪ a month · up to 5 family members',
    familyFeatures: ['Everything in Premium, for everyone', 'Up to 5 family members', 'Everyone keeps their own settings and language'],
    ribbon: 'Recommended',
    join: 'Join',
    current: 'Your current plan',
    joinPremium: 'Join Premium',
    renew: 'Renews automatically. Cancel anytime in the store settings.',
    supporter: 'Supporter',
    thanks: 'You’re a supporter. Thank you.',
    activePremium: 'Your subscription is active: no ads, the whole archive and search.',
    activeFamilyOwner: 'Your family plan is active. You can invite up to 4 family members.',
    activeFamilyMember: 'You’re part of a family plan: no ads, the whole archive and search.',
    manageFamily: 'Manage family members',
    donateLead: 'Want to support us without a subscription?',
    donate: 'Donate to the association',
    soonTitle: 'Subscriptions open soon',
    soonText: 'Soon you’ll be able to join Premium and the family plan right in the app, through Google Play.',
    soonWhatsapp: 'Already a Premium subscriber on WhatsApp? You’re recognized automatically by your phone number: sign in with the same number and your subscription is active.',
    soonDonate: 'Want to support us now? You can donate to the association.',
    ok: 'Got it',
  },
  fr: {
    close: 'Fermer',
    title: 'Sans publicité. Avec toutes les archives.',
    subtitle: 'L’abonnement finance le service et garde l’information propre, pour vous et pour tous.',
    premiumName: 'Premium',
    premiumPrice: '[prix] ₪ par mois',
    premiumFeatures: ['Aucune publicité', 'Toutes les archives, avec recherche', 'Badge de soutien sur votre profil'],
    familyName: 'Famille',
    familyPrice: '[prix] ₪ par mois · jusqu’à 5 membres',
    familyFeatures: ['Tout Premium, pour chacun', 'Jusqu’à 5 membres de la famille', 'Chacun garde ses réglages et sa langue'],
    ribbon: 'Recommandé',
    join: 'S’abonner',
    current: 'Votre formule actuelle',
    joinPremium: 'Passer à Premium',
    renew: 'Renouvellement automatique. Résiliable à tout moment dans les réglages du store.',
    supporter: 'Soutien',
    thanks: 'Vous nous soutenez. Merci.',
    activePremium: 'Votre abonnement est actif : sans publicité, toutes les archives et la recherche.',
    activeFamilyOwner: 'Votre abonnement famille est actif. Vous pouvez inviter jusqu’à 4 membres.',
    activeFamilyMember: 'Vous faites partie d’un abonnement famille : sans publicité, toutes les archives et la recherche.',
    manageFamily: 'Gérer les membres',
    donateLead: 'Envie de nous soutenir sans abonnement ?',
    donate: 'Faire un don à l’association',
    soonTitle: 'Les abonnements ouvrent bientôt',
    soonText: 'Bientôt, vous pourrez souscrire à Premium et à l’abonnement famille directement dans l’application, via Google Play.',
    soonWhatsapp: 'Déjà abonné Premium sur WhatsApp ? Vous êtes reconnu automatiquement par votre numéro : connectez-vous avec le même numéro et l’abonnement est actif.',
    soonDonate: 'Envie de nous soutenir dès maintenant ? Vous pouvez faire un don à l’association.',
    ok: 'Compris',
  },
});

export const FAMILY_S = defineStrings({
  he: {
    title: 'מנוי משפחתי',
    ownerIntro: 'אפשר להזמין עד 4 בני משפחה. כל אחד נכנס לאפליקציה עם מספר הטלפון שלו ומקבל את כל מה שבפרימיום, עם ההגדרות והשפה שלו.',
    count: (n: number) => `${n} מתוך 5, כולל אתכם`,
    inviteTitle: 'הזמנת בן או בת משפחה',
    name: 'שם',
    phone: 'מספר טלפון',
    invite: 'להזמנה',
    members: 'בני המשפחה',
    you: 'אתם',
    owner: 'בעלי המנוי',
    invited: 'הוזמן/ה',
    joined: 'במנוי',
    remove: (name: string) => `הסרת ${name}`,
    removeTitle: 'להסיר מהמנוי המשפחתי?',
    removeText: (name: string) => `הפרימיום של ${name} דרך המנוי המשפחתי יסתיים. אפשר להזמין שוב בכל עת.`,
    removeConfirm: 'להסרה',
    cancel: 'ביטול',
    sendWhatsapp: 'לשליחת הזמנה בוואטסאפ',
    waText: (name: string) =>
      `היי ${name}, הוספתי אותך למנוי המשפחתי שלי בתמצית החדשות. מורידים את האפליקציה ונכנסים עם מספר הטלפון שלך, והפרימיום כבר פעיל. https://tamzit.org.il`,
    invitedOk: (name: string) => `${name} נוסף/ה למנוי. אפשר לשלוח הודעה בוואטסאפ.`,
    empty: 'עוד לא הזמנתם אף אחד.',
    full: 'המנוי המשפחתי מלא. כדי להזמין מישהו אחר, הסירו קודם אחד מבני המשפחה.',
    errName: 'נא לכתוב שם',
    errPhone: 'מספר הטלפון לא תקין',
    errFull: 'המנוי המשפחתי מלא',
    errOwner: 'רק בעלי המנוי המשפחתי יכולים להזמין',
    errGeneric: 'לא הצלחנו. נסו שוב.',
    loadError: 'לא הצלחנו לטעון את בני המשפחה.',
    retry: 'נסו שוב',
    memberTitle: 'אתם במנוי משפחתי',
    memberText: 'בלי פרסומות, כל הארכיון והחיפוש, עם ההגדרות והשפה שלכם. את המנוי מנהלים בעלי המנוי.',
    otherTitle: 'מנוי אחד לכל המשפחה',
    otherText: 'במנוי המשפחתי עד 5 בני משפחה מקבלים את כל מה שבפרימיום: בלי פרסומות, כל הארכיון והחיפוש. כל אחד נכנס עם מספר הטלפון שלו, עם ההגדרות והשפה שלו.',
    toPremium: 'לפרטים על המנוי',
  },
  en: {
    title: 'Family plan',
    ownerIntro: 'You can invite up to 4 family members. Each one signs in with their own phone number and gets everything in Premium, with their own settings and language.',
    count: (n: number) => `${n} of 5, including you`,
    inviteTitle: 'Invite a family member',
    name: 'Name',
    phone: 'Phone number',
    invite: 'Invite',
    members: 'Family members',
    you: 'You',
    owner: 'Plan owner',
    invited: 'Invited',
    joined: 'Joined',
    remove: (name: string) => `Remove ${name}`,
    removeTitle: 'Remove from the family plan?',
    removeText: (name: string) => `${name}’s Premium through your family plan will end. You can invite them again anytime.`,
    removeConfirm: 'Remove',
    cancel: 'Cancel',
    sendWhatsapp: 'Send the invitation on WhatsApp',
    waText: (name: string) =>
      `Hi ${name}, I added you to my Tamzit family plan. Download the app and sign in with your phone number, and Premium is already on. https://tamzit.org.il`,
    invitedOk: (name: string) => `${name} was added to the plan. You can send them a WhatsApp message.`,
    empty: 'You haven’t invited anyone yet.',
    full: 'Your family plan is full. To invite someone else, remove a member first.',
    errName: 'Please enter a name',
    errPhone: 'Invalid phone number',
    errFull: 'The family plan is full',
    errOwner: 'Only the family plan owner can invite',
    errGeneric: 'Something went wrong. Please try again.',
    loadError: 'We couldn’t load your family members.',
    retry: 'Try again',
    memberTitle: 'You’re on a family plan',
    memberText: 'No ads, the whole archive and search, with your own settings and language. The plan owner manages the subscription.',
    otherTitle: 'One plan for the whole family',
    otherText: 'With the family plan, up to 5 family members get everything in Premium: no ads, the whole archive and search. Each one signs in with their own phone number, settings and language.',
    toPremium: 'About the plans',
  },
  fr: {
    title: 'Abonnement famille',
    ownerIntro: 'Vous pouvez inviter jusqu’à 4 membres de votre famille. Chacun se connecte avec son propre numéro et profite de tout Premium, avec ses réglages et sa langue.',
    count: (n: number) => `${n} sur 5, vous compris`,
    inviteTitle: 'Inviter un membre de la famille',
    name: 'Nom',
    phone: 'Numéro de téléphone',
    invite: 'Inviter',
    members: 'Membres de la famille',
    you: 'Vous',
    owner: 'Titulaire',
    invited: 'Invité',
    joined: 'Inscrit',
    remove: (name: string) => `Retirer ${name}`,
    removeTitle: 'Retirer de l’abonnement famille ?',
    removeText: (name: string) => `Le Premium de ${name} via votre abonnement famille prendra fin. Vous pourrez l’inviter à nouveau à tout moment.`,
    removeConfirm: 'Retirer',
    cancel: 'Annuler',
    sendWhatsapp: 'Envoyer l’invitation sur WhatsApp',
    waText: (name: string) =>
      `Bonjour ${name}, je t’ai ajouté à mon abonnement famille Tamzit. Télécharge l’application et connecte-toi avec ton numéro : le Premium est déjà actif. https://tamzit.org.il`,
    invitedOk: (name: string) => `${name} a été ajouté à l’abonnement. Vous pouvez lui envoyer un message WhatsApp.`,
    empty: 'Vous n’avez encore invité personne.',
    full: 'Votre abonnement famille est complet. Pour inviter quelqu’un d’autre, retirez d’abord un membre.',
    errName: 'Veuillez indiquer un nom',
    errPhone: 'Numéro de téléphone invalide',
    errFull: 'L’abonnement famille est complet',
    errOwner: 'Seul le titulaire de l’abonnement famille peut inviter',
    errGeneric: 'Une erreur est survenue. Veuillez réessayer.',
    loadError: 'Impossible de charger les membres de la famille.',
    retry: 'Réessayer',
    memberTitle: 'Vous faites partie d’un abonnement famille',
    memberText: 'Sans publicité, toutes les archives et la recherche, avec vos réglages et votre langue. Le titulaire gère l’abonnement.',
    otherTitle: 'Un abonnement pour toute la famille',
    otherText: 'Avec l’abonnement famille, jusqu’à 5 membres profitent de tout Premium : sans publicité, toutes les archives et la recherche. Chacun se connecte avec son numéro, ses réglages et sa langue.',
    toPremium: 'Voir les formules',
  },
});

export const DONATE_S = defineStrings({
  he: {
    title: 'תרומה לעמותה',
    cardTitle: 'תמיכה בעמותה',
    cardText: 'תמצית החדשות היא מחלקה של עמותת לוקחים אחריות. תרומה מאפשרת לנו להמשיך לכתוב חדשות נקיות, בלי רעש ובלי פושים.',
    kind: 'סוג התרומה',
    once: 'חד־פעמית',
    monthly: 'חודשית',
    amount: 'סכום',
    other: 'סכום אחר',
    otherLabel: 'סכום בשקלים',
    cta: (n: number) => `לתרומה של ₪${n}`,
    ctaMonthly: (n: number) => `לתרומה חודשית של ₪${n}`,
    ctaEmpty: 'לתרומה',
    secure: 'התרומה עוברת בדף תרומה מאובטח של העמותה, בדפדפן.',
    about: 'לוקחים אחריות פועלת לשימוש בריא ומאוזן ברשת ובמדיה. תמצית החדשות היא אחת המחלקות הגדולות שלה.',
    parentLabel: 'לוקחים אחריות',
    errAmount: 'נא לכתוב סכום',
    errOpen: 'לא הצלחנו לפתוח את דף התרומה. נסו שוב.',
    thanks: 'תודה על התמיכה.',
  },
  en: {
    title: 'Donate',
    cardTitle: 'Support the association',
    cardText: 'Tamzit is a department of the Lokchim Achrayut association. Donations let us keep writing clean news, without the noise and without pushy alerts.',
    kind: 'Donation type',
    once: 'One-time',
    monthly: 'Monthly',
    amount: 'Amount',
    other: 'Other amount',
    otherLabel: 'Amount in shekels',
    cta: (n: number) => `Donate ₪${n}`,
    ctaMonthly: (n: number) => `Donate ₪${n} a month`,
    ctaEmpty: 'Donate',
    secure: 'Donations go through the association’s secure donation page, in your browser.',
    about: 'Lokchim Achrayut works for healthy, balanced use of the internet and media. Tamzit is one of its largest departments.',
    parentLabel: 'Lokchim Achrayut',
    errAmount: 'Please enter an amount',
    errOpen: 'We couldn’t open the donation page. Please try again.',
    thanks: 'Thank you for your support.',
  },
  fr: {
    title: 'Faire un don',
    cardTitle: 'Soutenir l’association',
    cardText: 'Tamzit est un département de l’association Lokchim Achrayout. Les dons nous permettent de continuer à écrire une information propre, sans bruit et sans alertes intrusives.',
    kind: 'Type de don',
    once: 'Ponctuel',
    monthly: 'Mensuel',
    amount: 'Montant',
    other: 'Autre montant',
    otherLabel: 'Montant en shekels',
    cta: (n: number) => `Donner ${n} ₪`,
    ctaMonthly: (n: number) => `Donner ${n} ₪ par mois`,
    ctaEmpty: 'Faire un don',
    secure: 'Le don se fait sur la page de don sécurisée de l’association, dans votre navigateur.',
    about: 'Lokchim Achrayout œuvre pour un usage sain et équilibré d’internet et des médias. Tamzit est l’un de ses principaux départements.',
    parentLabel: 'Lokchim Achrayout',
    errAmount: 'Veuillez indiquer un montant',
    errOpen: 'Impossible d’ouvrir la page de don. Veuillez réessayer.',
    thanks: 'Merci pour votre soutien.',
  },
});
