import { defineStrings } from '@/lib/i18n';

export const SearchStrings = defineStrings({
  he: {
    title: 'חיפוש בארכיון',
    label: 'חיפוש בכל הידיעות',
    placeholder: 'מה לחפש?',
    clear: 'ניקוי החיפוש',
    searching: 'מחפשים',
    recent: 'חיפושים אחרונים',
    clearRecent: 'ניקוי',
    clearRecentLabel: 'ניקוי החיפושים האחרונים',
    introTitle: 'חיפוש בכל הידיעות',
    introText: 'מחפשים בכותרות ובגוף הידיעות, בכל הארכיון.',
    minChars: 'הקלידו לפחות 2 אותיות',
    results: (n: number) => (n === 1 ? 'תוצאה אחת' : `${n} תוצאות`),
    more: 'עוד תוצאות',
    noResultsTitle: (q: string) => `לא מצאנו ידיעות על "${q}"`,
    noResultsText: 'נסו מילה אחרת או כתיב אחר.',
    upsellTitle: 'החיפוש זמין במנוי פרימיום',
    upsellText: 'חיפוש בכל הידיעות, בכותרת ובגוף, והארכיון המלא של כל המהדורות.',
    details: 'לפרטים',
    error: 'החיפוש לא הצליח. בדקו את החיבור ונסו שוב.',
    retry: 'נסו שוב',
  },
  en: {
    title: 'Search the archive',
    label: 'Search all news items',
    placeholder: 'What are you looking for?',
    clear: 'Clear search',
    searching: 'Searching',
    recent: 'Recent searches',
    clearRecent: 'Clear',
    clearRecentLabel: 'Clear recent searches',
    introTitle: 'Search every item',
    introText: 'We search headlines and text across the whole archive.',
    minChars: 'Type at least 2 letters',
    results: (n: number) => (n === 1 ? '1 result' : `${n} results`),
    more: 'More results',
    noResultsTitle: (q: string) => `No items found for "${q}"`,
    noResultsText: 'Try another word or spelling.',
    upsellTitle: 'Search comes with Premium',
    upsellText: 'Search every item, headline and text, plus the full archive of every edition.',
    details: 'Learn more',
    error: "Search didn't work. Check your connection and try again.",
    retry: 'Try again',
  },
  fr: {
    title: 'Rechercher dans les archives',
    label: 'Rechercher dans tous les articles',
    placeholder: 'Que cherchez-vous ?',
    clear: 'Effacer la recherche',
    searching: 'Recherche en cours',
    recent: 'Recherches récentes',
    clearRecent: 'Effacer',
    clearRecentLabel: 'Effacer les recherches récentes',
    introTitle: 'Rechercher dans tous les articles',
    introText: 'La recherche porte sur les titres et le texte, dans toutes les archives.',
    minChars: 'Tapez au moins 2 lettres',
    results: (n: number) => (n === 1 ? '1 résultat' : `${n} résultats`),
    more: 'Plus de résultats',
    noResultsTitle: (q: string) => `Aucun article trouvé pour « ${q} »`,
    noResultsText: 'Essayez un autre mot ou une autre orthographe.',
    upsellTitle: 'La recherche est incluse dans Premium',
    upsellText: 'Recherchez dans tous les articles, titres et texte, et accédez aux archives complètes.',
    details: 'En savoir plus',
    error: "La recherche n'a pas abouti. Vérifiez votre connexion et réessayez.",
    retry: 'Réessayer',
  },
});
