import { defineStrings } from '@/lib/i18n';

export const SHABBAT_S = defineStrings({
  he: {
    shabbat: 'שבת שלום',
    chag: 'חג שמח',
    shabbatChag: 'שבת שלום וחג שמח',
    yomKippur: 'גמר חתימה טובה',
    roshHashana: 'שנה טובה',
    shabbatRoshHashana: 'שבת שלום ושנה טובה',
    textShabbat: 'תמצית החדשות נחה בשבת. אין מהדורות ואין התראות עד צאת השבת.',
    textChag: 'תמצית החדשות נחה בחג. אין מהדורות ואין התראות עד צאת החג.',
    textShabbatChag: 'תמצית החדשות נחה בשבת ובחג. אין מהדורות ואין התראות עד צאת השבת והחג.',
    textYomKippur: 'תמצית החדשות נחה ביום הכיפורים. אין מהדורות ואין התראות עד צאת הצום.',
    nextShabbat: (city: string) => `מהדורת מוצאי שבת · ${city}`,
    nextChag: (city: string) => `מהדורת מוצאי החג · ${city}`,
    endsShabbat: (t: string) => `צאת השבת ${t}`,
    endsChag: (t: string) => `צאת החג ${t}`,
    archive: 'לקריאה במהדורות קודמות',
  },
  en: {
    shabbat: 'Shabbat shalom',
    chag: 'Chag sameach',
    shabbatChag: 'Shabbat shalom and chag sameach',
    yomKippur: 'Gmar chatima tova',
    roshHashana: 'Shana tova',
    shabbatRoshHashana: 'Shabbat shalom and shana tova',
    textShabbat: 'Tamzit rests on Shabbat. No editions and no notifications until Shabbat ends.',
    textChag: 'Tamzit rests on the holiday. No editions and no notifications until the holiday ends.',
    textShabbatChag: 'Tamzit rests on Shabbat and the holiday. No editions and no notifications until they end.',
    textYomKippur: 'Tamzit rests on Yom Kippur. No editions and no notifications until the fast ends.',
    nextShabbat: (city: string) => `Motzei Shabbat edition · ${city}`,
    nextChag: (city: string) => `After-holiday edition · ${city}`,
    endsShabbat: (t: string) => `Shabbat ends ${t}`,
    endsChag: (t: string) => `Holiday ends ${t}`,
    archive: 'Read earlier editions',
  },
  fr: {
    shabbat: 'Chabbat chalom',
    chag: 'Hag saméah',
    shabbatChag: 'Chabbat chalom et hag saméah',
    yomKippur: 'Gmar hatima tova',
    roshHashana: 'Chana tova',
    shabbatRoshHashana: 'Chabbat chalom et chana tova',
    textShabbat: 'Tamzit se repose pendant Chabbat. Pas d’édition ni de notification avant la fin de Chabbat.',
    textChag: 'Tamzit se repose pendant la fête. Pas d’édition ni de notification avant la fin de la fête.',
    textShabbatChag: 'Tamzit se repose pendant Chabbat et la fête. Pas d’édition ni de notification avant leur fin.',
    textYomKippur: 'Tamzit se repose à Yom Kippour. Pas d’édition ni de notification avant la fin du jeûne.',
    nextShabbat: (city: string) => `Édition de Motsaé Chabbat · ${city}`,
    nextChag: (city: string) => `Édition de fin de fête · ${city}`,
    endsShabbat: (t: string) => `Fin de Chabbat ${t}`,
    endsChag: (t: string) => `Fin de la fête ${t}`,
    archive: 'Lire les éditions précédentes',
  },
});
