import { defineStrings } from '@/lib/i18n';

const heCount = (n: number) => (n === 1 ? 'ידיעה אחת' : `${n} ידיעות`);
const enCount = (n: number) => (n === 1 ? '1 item' : `${n} items`);
const frCount = (n: number) => (n === 1 ? '1 article' : `${n} articles`);
// The free archive span (app setting free_archive_days) in words: a week for 7, a day for 1, else n days.
const heSpan = (n: number) => (n === 7 ? 'משבוע' : n === 1 ? 'מיום' : `מ־${n} ימים`);
const enSpan = (n: number) => (n === 7 ? 'a week' : n === 1 ? 'a day' : `${n} days`);
const frSpan = (n: number) => (n === 7 ? "d'une semaine" : n === 1 ? "d'un jour" : `de ${n} jours`);

export const S = defineStrings({
  he: {
    appTitle: 'תמצית החדשות',
    textSize: (pct: number) => `גודל טקסט, ${pct}%`,
    meta: (n: number, m: number) => `${heCount(n)} · ${m} דק׳ קריאה`,
    listen: 'האזנה',
    special: 'עדכון מיוחד',
    earlierSpecials: 'עדכונים מיוחדים מלפני המהדורה',
    ad: 'פרסומת',
    adOf: (label: string, sponsor: string) => `${label}: ${sponsor}`,
    adOpens: (host: string) => `פתיחת ${host} בדפדפן`,
    removeAds: 'להסרת פרסומות',
    community: (name: string) => `בקהילה שלך · ${name}`,
    goodNews: 'ונסיים בטוב',
    endTitle: 'זהו, אתם מעודכנים',
    endText: 'אין מה לגלול יותר. אפשר להניח את הטלפון ולחזור לחיים.',
    next: (name: string, time: string) => `הבאה: ${name} · ${time}`,
    emptyCritical: 'אין היום חדש קריטי. זה בסדר.',
    emptyCriticalText: 'בחרתם לקבל רק ידיעות קריטיות. אפשר לשנות את זה בהגדרות.',
    emptyGeneric: 'אין עדיין ידיעות במהדורה',
    emptyGenericText: 'כשיתפרסמו ידיעות חדשות, הן יופיעו כאן במהדורה הבאה.',
    offline: 'אין חיבור. מוצגת המהדורה האחרונה ששמרנו.',
    loadError: 'לא הצלחנו לטעון את המהדורה.',
    retry: 'נסו שוב',
    lockedTitle: (n: number) => (n === 0 ? 'מהדורות קודמות זמינות בפרימיום' : `מהדורות מלפני יותר ${heSpan(n)} זמינות בפרימיום`),
    lockedText: 'בפרימיום כל הארכיון פתוח, עם חיפוש ובלי פרסומות.',
    lockedCta: 'לפרטים',
    notFound: 'המהדורה לא נמצאה',
    loading: 'טוענים את המהדורה',
  },
  en: {
    appTitle: 'Tamzit News',
    textSize: (pct: number) => `Text size, ${pct}%`,
    meta: (n: number, m: number) => `${enCount(n)} · ${m} min read`,
    listen: 'Listen',
    special: 'Special update',
    earlierSpecials: 'Special updates before this edition',
    ad: 'Advertisement',
    adOf: (label: string, sponsor: string) => `${label}: ${sponsor}`,
    adOpens: (host: string) => `Opens ${host} in the browser`,
    removeAds: 'Remove ads',
    community: (name: string) => `In your community · ${name}`,
    goodNews: 'Ending on a good note',
    endTitle: "That's it, you're up to date",
    endText: 'Nothing more to scroll. You can put the phone down and get back to your day.',
    next: (name: string, time: string) => `Next: ${name} · ${time}`,
    emptyCritical: "Nothing critical today. That's fine.",
    emptyCriticalText: 'You chose to receive critical items only. You can change this in Settings.',
    emptyGeneric: 'No items in this edition yet',
    emptyGenericText: 'New items will appear here in your next edition.',
    offline: 'No connection. Showing the last edition we saved.',
    loadError: "We couldn't load the edition.",
    retry: 'Try again',
    lockedTitle: (n: number) => (n === 0 ? 'Past editions are available with Premium' : `Editions older than ${enSpan(n)} are available with Premium`),
    lockedText: 'Premium opens the full archive, with search and no ads.',
    lockedCta: 'Learn more',
    notFound: 'Edition not found',
    loading: 'Loading the edition',
  },
  fr: {
    appTitle: 'Tamzit News',
    textSize: (pct: number) => `Taille du texte, ${pct} %`,
    meta: (n: number, m: number) => `${frCount(n)} · ${m} min de lecture`,
    listen: 'Écouter',
    special: 'Mise à jour spéciale',
    earlierSpecials: 'Mises à jour spéciales avant cette édition',
    ad: 'Publicité',
    adOf: (label: string, sponsor: string) => `${label} : ${sponsor}`,
    adOpens: (host: string) => `Ouvre ${host} dans le navigateur`,
    removeAds: 'Supprimer les publicités',
    community: (name: string) => `Dans votre communauté · ${name}`,
    goodNews: 'Pour finir en beauté',
    endTitle: "C'est tout, vous êtes à jour",
    endText: 'Plus rien à faire défiler. Vous pouvez poser le téléphone et reprendre votre journée.',
    next: (name: string, time: string) => `Prochaine : ${name} · ${time}`,
    emptyCritical: "Rien de critique aujourd'hui. C'est très bien.",
    emptyCriticalText: 'Vous recevez uniquement les articles critiques. Vous pouvez changer cela dans les réglages.',
    emptyGeneric: "Pas encore d'articles dans cette édition",
    emptyGenericText: 'Les nouveaux articles apparaîtront ici dans votre prochaine édition.',
    offline: 'Pas de connexion. Voici la dernière édition enregistrée.',
    loadError: "Impossible de charger l'édition.",
    retry: 'Réessayer',
    lockedTitle: (n: number) =>
      n === 0 ? 'Les éditions passées sont disponibles avec Premium' : `Les éditions de plus ${frSpan(n)} sont disponibles avec Premium`,
    lockedText: "Premium ouvre toutes les archives, avec la recherche et sans publicité.",
    lockedCta: 'En savoir plus',
    notFound: 'Édition introuvable',
    loading: "Chargement de l'édition",
  },
});
