import { defineStrings } from '@/lib/i18n';

export const SETTINGS_S = defineStrings({
  he: {
    title: 'הגדרות',
    supporter: 'תומך/ת',
    guest: 'אורח/ת',
    signIn: 'כניסה או הרשמה',
    signInHint: 'לסנכרון ההגדרות, לפרימיום ולתשובות מהעורכים',
    // groups
    gEditions: 'המהדורות שלי',
    gNotifications: 'התראות',
    gReading: 'קריאה ותצוגה',
    gShabbat: 'שבת וחגים',
    gSupport: 'מנוי ותמיכה',
    gAccount: 'חשבון',
    gAbout: 'אודות',
    // rows
    language: 'שפה',
    track: 'מסלול',
    topics: 'נושאים',
    rhythm: 'תדירות ושעות',
    level: 'רמת ידיעות',
    style: 'סגנון',
    communities: 'מהדורות קהילתיות',
    communitiesSub: 'חדשות מקומיות בסוף כל מהדורה',
    notifications: 'התראות',
    textSize: 'גודל טקסט',
    theme: 'ערכת צבעים',
    shabbatMode: 'מצב שבת וחגים',
    alwaysOn: 'תמיד פעיל',
    shabbatCity: 'זמני שבת לפי',
    premium: 'פרימיום',
    family: 'מנוי משפחתי',
    donate: 'תרומה לעמותה',
    personal: 'פרטים אישיים',
    messages: 'הודעות מהעורכים',
    aboutApp: 'אודות תמצית החדשות',
    licenses: 'רישיונות',
    // values
    topicsCount: (n: number) => `${n} נבחרו`,
    topicsAll: 'כל הנושאים',
    perDay: (n: number) => (n === 1 ? 'פעם ביום' : n === 2 ? 'פעמיים ביום' : `${n} ביום`),
    none: 'בלי',
    communitiesCount: (n: number) => `${n} קהילות`,
    notifOn: 'פועלות',
    notifOff: 'כבויות',
    notifEditionsOnly: 'רק מהדורות',
    notifSpecialOnly: 'רק עדכון מיוחד',
    notifBlocked: 'כבויות במכשיר',
    premiumActive: 'פעיל',
    premiumFamily: 'משפחתי',
    premiumInactive: 'לא פעיל',
    familyCount: (n: number) => `${n} מתוך 5`,
    familyMember: 'חלק ממשפחה',
    unread: (n: number) => (n === 1 ? 'הודעה חדשה' : `${n} חדשות`),
    themeSystem: 'מערכת',
    themeLight: 'בהיר',
    themeDark: 'כהה',
    loadError: 'לא הצלחנו לטעון את ההגדרות.',
    retry: 'נסו שוב',
    // sub-screens
    effective: (when: string) => `השינוי ייכנס לתוקף מהמהדורה הבאה, ${when}.`,
    whenToday: (t: string) => `ב־${t}`,
    whenTomorrow: (t: string) => `מחר ב־${t}`,
    whenDay: (day: string, t: string) => `ב${day} ב־${t}`,
    saving: 'שומרים',
    saved: 'נשמר',
    saveError: 'לא הצלחנו לשמור. נסו שוב.',
    languageNote: 'שפת המהדורה היא גם שפת האפליקציה. מעבר בין עברית לשפה אחרת טוען את האפליקציה מחדש.',
    trackNote: 'מסלול הנוער מיועד לגילאי \u206610–15\u2069: ידיעות שנכתבו לבני נוער.',
    topicsNote: 'ידיעות קריטיות מגיעות תמיד, מכל נושא.',
    levelNote: 'ידיעות קריטיות מגיעות תמיד, בכל רמה שתבחרו.',
    styleNote: 'כך ייכתבו הידיעות במהדורה שלכם. הכרטיס הנבחר מציג דוגמה.',
  },
  en: {
    title: 'Settings',
    supporter: 'Supporter',
    guest: 'Guest',
    signIn: 'Sign in or register',
    signInHint: 'To sync your settings, get Premium and receive editor replies',
    gEditions: 'My editions',
    gNotifications: 'Notifications',
    gReading: 'Reading and display',
    gShabbat: 'Shabbat and holidays',
    gSupport: 'Subscription and support',
    gAccount: 'Account',
    gAbout: 'About',
    language: 'Language',
    track: 'Track',
    topics: 'Topics',
    rhythm: 'Frequency and times',
    level: 'News level',
    style: 'Style',
    communities: 'Community editions',
    communitiesSub: 'Local news at the end of every edition',
    notifications: 'Notifications',
    textSize: 'Text size',
    theme: 'Theme',
    shabbatMode: 'Shabbat and holiday mode',
    alwaysOn: 'Always on',
    shabbatCity: 'Shabbat times for',
    premium: 'Premium',
    family: 'Family plan',
    donate: 'Donate',
    personal: 'Personal details',
    messages: 'Messages from the editors',
    aboutApp: 'About Tamzit',
    licenses: 'Licenses',
    topicsCount: (n: number) => `${n} selected`,
    topicsAll: 'All topics',
    perDay: (n: number) => (n === 1 ? 'Once a day' : n === 2 ? 'Twice a day' : `${n} a day`),
    none: 'None',
    communitiesCount: (n: number) => `${n} communities`,
    notifOn: 'On',
    notifOff: 'Off',
    notifEditionsOnly: 'Editions only',
    notifSpecialOnly: 'Special updates only',
    notifBlocked: 'Off on this device',
    premiumActive: 'Active',
    premiumFamily: 'Family',
    premiumInactive: 'Not active',
    familyCount: (n: number) => `${n} of 5`,
    familyMember: 'Family member',
    unread: (n: number) => `${n} new`,
    themeSystem: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    loadError: 'We couldn’t load your settings.',
    retry: 'Try again',
    effective: (when: string) => `The change takes effect from your next edition, ${when}.`,
    whenToday: (t: string) => `at ${t}`,
    whenTomorrow: (t: string) => `tomorrow at ${t}`,
    whenDay: (day: string, t: string) => `on ${day} at ${t}`,
    saving: 'Saving',
    saved: 'Saved',
    saveError: 'We couldn’t save. Please try again.',
    languageNote: 'Your edition language is also the app language. Switching between Hebrew and another language reloads the app.',
    trackNote: 'The youth track is for ages \u206610–15\u2069: news written for young readers.',
    topicsNote: 'Critical news always comes through, from any topic.',
    levelNote: 'Critical news always comes through, whatever level you choose.',
    styleNote: 'This is how the news in your edition will be written. The selected card shows an example.',
  },
  fr: {
    title: 'Réglages',
    supporter: 'Soutien',
    guest: 'Invité',
    signIn: 'Connexion ou inscription',
    signInHint: 'Pour synchroniser vos réglages, passer Premium et recevoir les réponses de la rédaction',
    gEditions: 'Mes éditions',
    gNotifications: 'Notifications',
    gReading: 'Lecture et affichage',
    gShabbat: 'Chabbat et fêtes',
    gSupport: 'Abonnement et soutien',
    gAccount: 'Compte',
    gAbout: 'À propos',
    language: 'Langue',
    track: 'Parcours',
    topics: 'Sujets',
    rhythm: 'Fréquence et horaires',
    level: 'Niveau d’information',
    style: 'Style',
    communities: 'Éditions locales',
    communitiesSub: 'L’actualité locale à la fin de chaque édition',
    notifications: 'Notifications',
    textSize: 'Taille du texte',
    theme: 'Thème',
    shabbatMode: 'Mode Chabbat et fêtes',
    alwaysOn: 'Toujours actif',
    shabbatCity: 'Horaires de Chabbat pour',
    premium: 'Premium',
    family: 'Abonnement famille',
    donate: 'Faire un don',
    personal: 'Informations personnelles',
    messages: 'Messages de la rédaction',
    aboutApp: 'À propos de Tamzit',
    licenses: 'Licences',
    topicsCount: (n: number) => `${n} choisis`,
    topicsAll: 'Tous les sujets',
    perDay: (n: number) => (n === 1 ? 'Une fois par jour' : n === 2 ? 'Deux fois par jour' : `${n} fois par jour`),
    none: 'Aucune',
    communitiesCount: (n: number) => `${n} communautés`,
    notifOn: 'Activées',
    notifOff: 'Désactivées',
    notifEditionsOnly: 'Éditions seulement',
    notifSpecialOnly: 'Mises à jour spéciales seulement',
    notifBlocked: 'Désactivées sur l’appareil',
    premiumActive: 'Actif',
    premiumFamily: 'Famille',
    premiumInactive: 'Inactif',
    familyCount: (n: number) => `${n} sur 5`,
    familyMember: 'Membre d’une famille',
    unread: (n: number) => (n === 1 ? '1 nouveau' : `${n} nouveaux`),
    themeSystem: 'Système',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    loadError: 'Impossible de charger vos réglages.',
    retry: 'Réessayer',
    effective: (when: string) => `Le changement s’appliquera à la prochaine édition, ${when}.`,
    whenToday: (t: string) => `à ${t}`,
    whenTomorrow: (t: string) => `demain à ${t}`,
    whenDay: (day: string, t: string) => `${day} à ${t}`,
    saving: 'Enregistrement',
    saved: 'Enregistré',
    saveError: 'Échec de l’enregistrement. Veuillez réessayer.',
    languageNote: 'La langue de l’édition est aussi celle de l’application. Passer de l’hébreu à une autre langue recharge l’application.',
    trackNote: 'Le parcours jeunesse s’adresse aux \u206610–15\u2069 ans : une actualité écrite pour eux.',
    topicsNote: 'Les informations critiques arrivent toujours, quel que soit le sujet.',
    levelNote: 'Les informations critiques arrivent toujours, quel que soit le niveau choisi.',
    styleNote: 'Voici comment seront écrites les informations de votre édition. La carte choisie montre un exemple.',
  },
});

/** Value labels for the preference rows. */
export const VALUE_LABELS = {
  language: { he: 'עברית', en: 'English', fr: 'Français' },
  audience: {
    he: { general: 'כללי', youth: 'נוער, \u206610–15\u2069' },
    en: { general: 'General', youth: 'Youth, \u206610–15\u2069' },
    fr: { general: 'Général', youth: 'Jeunesse, \u206610–15\u2069' },
  },
  level: {
    he: { critical: 'רק קריטיות', important: 'קריטיות וחשובות', general: 'הכל' },
    en: { critical: 'Critical only', important: 'Critical and important', general: 'Everything' },
    fr: { critical: 'Critiques seulement', important: 'Critiques et importantes', general: 'Tout' },
  },
  style: {
    he: { calm: 'מרגיע', human: 'אנושי', informative: 'אינפורמטיבי', light: 'קליל' },
    en: { calm: 'Calm', human: 'Human', informative: 'Informative', light: 'Light' },
    fr: { calm: 'Apaisant', human: 'Humain', informative: 'Informatif', light: 'Léger' },
  },
} as const;
